<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-linearalgebra-anushri666/blob/main/linear_algebra_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [ ]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

v_1 = [1, 0]^T becomes [2, 0]^T
Geometric meaning: Because this vector lies entirely on the x-axis, it is purely stretched horizontally by a factor of 2. Its direction remains unchanged.

v_2 = [0, 1]^T becomes [0, 3]^T
Geometric meaning: Because this vector lies entirely on the y-axis, it is purely stretched vertically by a factor of 3. Its direction remains unchanged.

v_3 = [1, 1]^T becomes [2, 3]^T
Geometric meaning: This vector is pulled both horizontally and vertically. Because the vertical stretch (3) is greater than the horizontal stretch (2), the vector is not only elongated but also tilted closer to the y-axis.

v_4 = [-2, 4]^T becomes [-4, 12]^T
Geometric meaning: Located in the second quadrant, its x-component is doubled (moving further left) and its y-component is tripled (moving much higher), significantly steepening its slope.

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.

The classmate is mistaken because matrix multiplication represents a geometric transformation of space. As proven in Part A, multiplying a vector by a matrix doesn't just change numbers randomly; it physically scales, rotates, or shears the vector relative to the coordinate axes.

In this specific case, matrix $A$ acts as a custom stretching machine that independently rescales the fabric of 2D space—doubling horizontal distances and tripling vertical distances. The numbers are simply the coordinates tracking where those physical points land after the space is stretched.

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [1]:
import numpy as np

def transform_vector(matrix, vector):
    # Ensure inputs are numpy arrays
    M = np.array(matrix)
    v = np.array(vector)

    # Perform the transformation
    transformed = M @ v

    # Print the individual component changes
    print(f"x changed from {v[0]} to {transformed[0]} (scaled by {matrix[0][0] if matrix[0][1]==0 else 'dynamic'}), "
          f"y changed from {v[1]} to {transformed[1]} (scaled by {matrix[1][1] if matrix[1][0]==0 else 'dynamic'}).")

    return transformed

# Example Usage:
A = [[2, 0], [0, 3]]
v3 = [1, 1]
transform_vector(A, v3)


x changed from 1 to 2 (scaled by 2), y changed from 1 to 3 (scaled by 3).


array([2, 3])

---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [4]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [3]:
import numpy as np

# Define user taste matrix
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5]   # User D
])

# Single NumPy operation for the full similarity matrix
similarity_matrix = users @ users.T
print(similarity_matrix)


[[1.5  0.5  1.48 1.  ]
 [0.5  1.5  0.52 1.  ]
 [1.48 0.52 1.5  1.  ]
 [1.   1.   1.   1.  ]]


**What linear algebra concept makes this possible in one line?**


The linear algebra concept that makes this possible in a single line is the matrix-matrix multiplication (or the outer dot product of a matrix with its transpose).

By multiplying the user matrix by its own transpose, we compute the dot product of every row (user) against every column (which is also every user).

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

*Write your answer here (double-click to edit this cell)*

In [5]:
# Look at the 4th row or column of the similarity matrix
print("User D similarities:", similarity_matrix[3])
# Output will show [1.0, 1.0, 1.0, 1.0] (ignoring User D with themselves, which is 1.0 here by coincidence because 4 * 0.25 = 1)


User D similarities: [1. 1. 1. 1.]


Geometric Reasoning: Yes, User D's similarity score with every other user will be identical.
The raw dot product calculates (sigma) (User_D_i x User_X_i).
Because User D has a constant value of 0.5 across all genres, the dot product simplifies to 0.5 X (sigma)(User_X_i). If you look at Users A, B, and C, the sum of their genre scores is exactly equal (0.9+0.1+0.8+0.2 = 2.0). Therefore, 0.5 x 2.0 = 1.0 for all of them.

### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

*Write your answer here (double-click to edit this cell)*

In [6]:
user_A = np.array([0.9, 0.1, 0.8, 0.2])
user_C = np.array([0.8, 0.2, 0.9, 0.1])
user_A_intense = np.array([1.8, 0.2, 1.6, 0.4])

# Even though A and C have almost identical tastes, look at raw dot products:
print("Dot product (A, C):", np.dot(user_A, user_C))          # Result: 1.48
print("Dot product (A_intense, C):", np.dot(user_A_intense, user_C))  # Result: 2.96

Dot product (A, C): 1.4800000000000002
Dot product (A_intense, C): 2.9600000000000004


1. The Problem: Raw dot products are sensitive to the magnitude (scale) of the vectors, not just the preference profile. If a user likes the exact same genres but happens to rate things more intensely (or consumes a lot more content), their vector magnitude increases, artificially inflating their similarity score.
2. Demonstration of the Flaw:
Let's introduce "User A-Intense", who has the exact same taste profile as User A but with doubled scores: [1.8, 0.2, 1.6, 0.4].
Flaw: User A-Intense appears "twice as similar" to User C than User A is, simply because their rating scales are larger.
3. Flaw: User A-Intense appears "twice as similar" to User C than User A is, simply because their rating scales are larger.The Fix (Cosine Similarity):We fix this by normalizing the vectors to unit length before taking the dot product, computing Cosine Similarity:
{Cosine Similarity} = (u.v)/(||u||x||v||)

In [7]:
# Function to normalize matrix rows to unit vectors
norms = np.linalg.norm(users, axis=1, keepdims=True)
normalized_users = users / norms

# Compute normalized similarity matrix
cosine_similarity_matrix = normalized_users @ normalized_users.T
print(cosine_similarity_matrix)

[[1.         0.33333333 0.98666667 0.81649658]
 [0.33333333 1.         0.34666667 0.81649658]
 [0.98666667 0.34666667 1.         0.81649658]
 [0.81649658 0.81649658 0.81649658 1.        ]]


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

*Write your answer here (double-click to edit this cell)*

After normalization, User A and User C are the most similar (excluding self-similarity).

Does this match intuition? Yes. Looking at the vectors, User A [0.9, 0.1, 0.8, 0.2] and User C [0.8, 0.2, 0.9, 0.1] both strongly prefer Action and Thriller, while strongly disliking Romance and Comedy. They have almost identical taste distributions.

Plain Language Meaning: In plain language, User A and User C share the same core entertainment preferences. They are both massive fans of high-octane, suspenseful storytelling (Action/Thriller) and share a mutual lack of interest in lighthearted or emotional content (Comedy/Romance). They would enjoy the exact same movie recommendations.

---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.